Questions - 1

In [ ]:
import pandas as pd
import numpy as np

np.random.seed(42)

data = np.random.rand(4, 4)
df = pd.DataFrame(data, columns = ['Feature1', 'Feature2', 'Feature3', 'Feature4'])
df

   Feature1  Feature2  Feature3  Feature4
0  0.374540  0.950714  0.731994  0.598658
1  0.156019  0.155995  0.058084  0.866176
2  0.601115  0.708073  0.020584  0.969910
3  0.832443  0.212339  0.181825  0.183405

Question - 2

In [ ]:
df = df.rename(columns ={
    'Feature1': 'Random value 1',
    'Feature2': 'Random value 2',
    'Feature3': 'Random value 3',
    'Feature4': 'Random value 4'
})
df

   Random value 1  Random value 2  Random value 3  Random value 4
0        0.374540        0.950714        0.731994        0.598658
1        0.156019        0.155995        0.058084        0.866176
2        0.601115        0.708073        0.020584        0.969910
3        0.832443        0.212339        0.181825        0.183405

Question - 3

In [ ]:
df.describe()

       Random value 1  Random value 2  Random value 3  Random value 4
count        4.000000        4.000000        4.000000        4.000000
mean         0.491029        0.506780        0.248122        0.654537
std          0.291252        0.386153        0.329856        0.350875
min          0.156019        0.155995        0.020584        0.183405
25%          0.319910        0.198253        0.048709        0.494845
50%          0.487828        0.460206        0.119954        0.732417
75%          0.658947        0.768733        0.319367        0.892110
max          0.832443        0.950714        0.731994        0.969910

Question - 4

In [ ]:
df.isnull()

   Random value 1  Random value 2  Random value 3  Random value 4
0           False           False           False           False
1           False           False           False           False
2           False           False           False           False
3           False           False           False           False

In [ ]:
df.isnull().sum()

Random value 1    0
Random value 2    0
Random value 3    0
Random value 4    0
dtype: int64

In [ ]:
df.dtypes

Random value 1    float64
Random value 2    float64
Random value 3    float64
Random value 4    float64
dtype: object

In [ ]:
df.loc[:, ['Random value 2', 'Random value 3']]

   Random value 2  Random value 3
0        0.950714        0.731994
1        0.155995        0.058084
2        0.708073        0.020584
3        0.212339        0.181825

In [ ]:
df.iloc[:, [1, 2]]

   Random value 2  Random value 3
0        0.950714        0.731994
1        0.155995        0.058084
2        0.708073        0.020584
3        0.212339        0.181825